### ISSUE TITLE
Tabular report API

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#100]
Looking at https://drive.google.com/file/d/0Bw_SC4mXFDn8ZTNaSUtpMnJhdm8/view?usp=sharing page 4

When I select a "School" (e.g. Humanities & Sciences) then I should be able to get a tabular report where the rows represent the departments in the school and the columns are counts of the number of Faculty, Articles, Journals, Grants and Citations and Collaborations in each department.

Additionally the results can be filtered by date (slider)

**Comment by cmh2166** [comment]
All of the CSV report requirements, based off of the use cases, are here: https://github.com/sul-dlss/rialto/wiki/Web-App-Data-Requirements#csv perhaps that is a better thing to guide these tickets?

**Comment by cmh2166** [comment]
Additionally, Collaborations is not a thing that exists in the requirements and so the data model.
