### ISSUE TITLE
confirm designs match requirements

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#102]
the RIALTO designs were originally made in october 2017, before we had confirmed requirements, and largely just copying Scholars@Cornell.

we need to revisit to see if it still matches the actual use cases we have and prioritizes the reports / visualizations we want for OIA in particular. there are also things, taken largely from Scholars@Cornell, that don't map to our requirements & thus our data model (i.e. 'Collaborations' facet).

blocks #100 related to #38 related to #129

**Comment by mjgiarlo** [comment]
@peetucket Can you take this one on? In addition to confirming the designs match our requirements, it would be super useful and timely if you could create a new section in the Web App Data Requirements document that lists a subset of the requirements that are high priorities for OIA for this work cycle: https://github.com/sul-dlss/rialto/wiki/Web-App-Data-Requirements

**Comment by peetucket** [comment]
Am confirming the top use cases (in Jira and duplicated here for sharing with stakeholders: https://docs.google.com/spreadsheets/d/1qMFY8Z-ndYSynMFZ-6lIMGhfhy79Hkr2WaerulXwJUA/edit#gid=0), focusing in particular on the described visualizations and tabular output.

**Comment by mjgiarlo** [comment]
@peetucket To clarify, by "top use cases" you mean "top **five** use cases?" Is that the right number?

**Comment by peetucket** [comment]
Yes, I was vague, but I have asked for clarification on the top 5.  Note it is somewhat arbitrary but still helpful to pick one I think (and I don't think our success/failure is defined by completing a specific number) as long as it is hopefully > 0.

**Comment by mjgiarlo** [comment]
@peetucket For now we are focusing on the top 1 (the one that explicitly mentions OIA). :cool: ?

**Comment by peetucket** [comment]
OK, I've confirmed we can focus on https://jirasul.stanford.edu/jira/browse/RIALTO-8 (collaboration heat map), with the others below that in the project board in priority order (https://jirasul.stanford.edu/jira/secure/RapidBoard.jspa?rapidView=921&view=planning).

While there is a UI design draft from Jennifer which sketches out a heat map (page 6 of the UI document: https://drive.google.com/open?id=0Bw_SC4mXFDn8ZTNaSUtpMnJhdm8),  it may not exactly match what is described in the use case.  For example, it groups departments by schools in a way that I'm not 100% sure we will have the data to do, and it also has a sort of nav bar above the map showing types of objects, which I'm not sure how that would work here.  

Personally, I don't think we should or need to wait for a UX person to make visual design comps that exactly match the use cases, but instead can use these initial design drafts as a guideline for a basic visual design.  Do we have the right skills on the team now to at least create basic HTML/CSS to match the general layout represented in the design comps and then make page modifications as needed driven by the descriptions in the actual cases.  If it helps, I am happy to create mockups in Balsamiq or something similar for the use cases we are working on and while not I'm not an HTML or CSS experts, am also happy to pair/work on the front end stuff.  

This model is similar to how Gary and I worked on the Revs Digital Library together...he created the general Rails layout and CSS, myself and Carrick would build the HTML pages to match requirements, and then Gary would come in as needed to cleanup or improve visual layout (and offer/make changes to improve usability).

**Comment by mjgiarlo** [comment]
@peetucket Thanks for confirming! Quick reply: we *do* have the hierarchy data around organizations (departments, divisions, schools) within the university. Good to know that displaying this hierarchy may not be a use case to prioritize for now. Agree that we don't need a UX person for this work cycle, since we're on the hook for a "basic" UI.

**Comment by mjgiarlo** [comment]
@cmh2166 Does :point_up: mean we can close this issue, or do you feel there's outstanding work here?

**Comment by cmh2166** [comment]
re-opening since in complete.

**Comment by cmh2166** [comment]
confirmed above convo, being documented here: https://github.com/sul-dlss/rialto/wiki/Web-App-Specs
