### ISSUE TITLE
Deploy RIALTO Ingest service to AWS dev environment

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#110]
this would just go to the ec2 instance currently able to connect to Neptune, and add rules to security group that allows access to that endpoint

Blocked by #114 Blocked by #117 Blocked by #112 Blocked by #111

**Comment by mjgiarlo** [comment]
The DLSS dev env does not use terraform, FYI. We still need repeatable deployment.

**Comment by mjgiarlo** [comment]
Closing per today's discussion at stand-up. This is done.
