### ISSUE TITLE
Add a Dev Readme

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#113]
Set up Dev Readme here for RIALTO core: RIALTO Ingest to Triplestore to SNS to Lambda to derivative stores

**Comment by aaron-collier** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/test-sam-cli.html

This looks like it may be a better way to test our lambda code as localstack doesn't provide sufficient debugging output.

**Comment by mjgiarlo** [comment]
Created a stub to hold this information: https://github.com/sul-dlss/rialto/wiki/Getting-Started-(Dev-Env)

**Comment by mjgiarlo** [comment]
I've finished a first draft of the dev README: https://github.com/sul-dlss/rialto/wiki/Getting-Started-(Dev-Env)

**Comment by mjgiarlo** [comment]
Closing this issue: https://github.com/sul-dlss/rialto/wiki/Getting-Started-(Dev-Env) is good enough for now, I am hearing. If folks would like specific additions or amendments to that doc, create a new issue and I'll have a look.
