### ISSUE TITLE
RIALTO Ingest Service to SNS

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#114]
Ingest Service _and_ sparql-loader.

message: json containing the following:

```
{ action: touch,
   entities:  [id, id, id]
   body: string
}
```

Action options:
- touch == C[R]UD on triples / rdf statements,
- delete == full entity delete (stretch goal, i.e. completely remove an entity graph)
- rebuild == full derivative dataset(s) rebuild. 
- others as needed for edge cases or to differentiate sparql-load from ingest-service

Entities: array of identifiers (URIs) that need to be updated / synced in derivative datastores. 

Body: full body of the ingest-service or sparql-load request (i.e. the POST's JSON or the SPARQL UPDATE request).

Supports both cases for generic re-trigger full re-derivation of data and specific re-derivation of subset of data, with focus on the latter.

**Comment by mjgiarlo** [comment]
The ingest service now supports the message spec above (though it only implements `touch`): https://github.com/sul-dlss-labs/rialto-ingest-service/pull/29

The sparql-loader component support is in progress and ticketed separately. https://github.com/sul-dlss/rialto/issues/137

Also copied the above text to our wiki: https://github.com/sul-dlss/rialto/wiki/RIALTO-Core-Messaging-Specification

Closing.
