### ISSUE TITLE
confirm AWS Stage, Prod envs access is just via terraform repo

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#119]
& confirm which terraform repo(s)? do we need console access too for anything (monitoring?) or just push AWS infrastructure changes to appropriate terraform repositories?

**Comment by aaron-collier** [comment]
With the DeveloperRole, we do not appear to be limited to any regions so I don't believe anything (outside of accepted practice) is limiting access.

**Comment by aaron-collier** [comment]
Ok, I believe this is confirmed and closable. The terraform-aws repository has development, staging, and production organizations, however in the console we do not (using the DeveloperRole) have access to change/review organizations. Changes to staging and production must happen through terraform-aws PRs. Development changes can be done in the console or through terraform.

The 2nd part here (monitoring) will be a new ticket.
