### ISSUE TITLE
Decide AWS Stage, Prod Environments Deployment Mechanism via Terraform

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#120]
How does code trigger changes to terraform to appropriate AWS environment? 

Blocked by #87 Blocked by #119

**Comment by aaron-collier** [comment]
Capturing this here, but will also review wiki locations: As of 7/12/18 - Neptune is not fully supported by Terraform. It is in progress: https://github.com/terraform-providers/terraform-provider-aws/issues/4713 but still open.

**Comment by mjgiarlo** [comment]
This is decided for all TF envs (Dev, Stage, and Prod): ops will apply TF updates after they merge PRs. Is/will be documented here: https://consul.stanford.edu/display/dlssdevops/Terraform+and+AWS

Closing.
