### ISSUE TITLE
Update architecture diagram with specifics & labels

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#122]
Please tick off your name in this list once you've reviewed the document per @cmh2166's request below. (And if you are the last person to tick off your name, pls close the issue. Thanks!)

- [x] @mjgiarlo
- [x] @jcoyne 
- [x] @aaron-collier 
- [x] @tingulfsen

**Comment by cmh2166** [comment]
WIP here: https://github.com/sul-dlss/rialto/wiki/RIALTO-Architecture

**Comment by cmh2166** [comment]
Would like devs to review with questions about naming of components, what "core includes", dataflow expectations, etc.

**Comment by jcoyne** [comment]
@cmh2166 I have some questions about the Lambda architecture.  I'm wondering why we don't send the entity directly to the lambda for update.  This would avoid an extra query/tranform step for each inserted document.

I'm also wondering how we know the affected URIs for a SPARQL update?  It seems like the proxy would have to parse the SPARQL and figure out if it could resolve which URIs are affected. Is that right?

If we're unable to determine affected URIs, do we need a mechanism for drop and rebuild the whole index?  If we do that, do we run into availability concerns during the rebuild?

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
>  It seems like the proxy would have to parse the SPARQL and figure out if it could resolve which URIs are affected. Is that right?

I think so, yes.

> If we're unable to determine affected URIs, do we need a mechanism for drop and rebuild the whole index?

Yes. Covered by this ticket: https://github.com/sul-dlss/rialto/issues/114

> If we do that, do we run into availability concerns during the rebuild?

That depends on how we rebuild. Could we reindex to a new core/collection and then swap them? Either using [collection aliases](https://lucene.apache.org/solr/guide/6_6/collections-api.html) or a [core swap](https://lucene.apache.org/solr/guide/6_6/coreadmin-api.html#CoreAdminAPI-SWAP)?

**Comment by jcoyne** [comment]
Parsing the SPARQL to determine affected subjects could be really hard if they don't explicitly supply a subject IRI in the SPARQL query.

**Comment by mjgiarlo** [comment]
@cmh2166 It looks great! Here are my questions for the team:

* Why does the SPARQL stack look so different from the JSON one? I wasn't expecting that. I perhaps naïvely assumed the SPARQL proxy would be an endpoint exposed by the Ingest service.
* I'm curious about the `Traject Combine` naming (vs. `RIALTO Combine` which I've seen elsewhere)
* How do folks feel about relabeling the Combine writers as loaders (aligning more closely with ETL terminology)?
* I believe the SPARQL stuff is in progress. @aaron-collier ?

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> Parsing the SPARQL to determine affected subjects could be really hard if they don't explicitly supply a subject IRI in the SPARQL query.

It could be. It's hard to say at this point. I have two thoughts about this:

* If the SPARQL proxy can't determine affected subjects, we may want to rebuild the index. (We may want to limit these rebuilds, too, but perhaps that is best taken up at a later date in another issue.)
* The "they" here is us. Specifically, the SPARQL loader component in the RIALTO Combine, so we do have control over this and should dig deeper when we work on said component.

**Comment by aaron-collier** [comment]
FYI @jcoyne and @mjgiarlo - the response I'm getting back from Neptune when doing an insert is:

```
2018/06/27 21:40:36 Response = [
{
    "type" : "UpdateEvent",
    "totalElapsedMillis" : 1,
    "elapsedMillis" : 0,
    "connFlush" : 0,
    "batchResolve" : 0,
    "whereClause" : 0,
    "deleteClause" : 0,
    "insertClause" : 0
},
{
    "type" : "Commit",
    "totalElapsedMillis" : 14
}
```

So unless this is configurable, I can really only determine that an update has happened (which may be sufficient), or send along the original SPARQL query... Or do the parsing in the proxy and send along any info we want. 

Something to discuss for sure.

**Comment by mjgiarlo** [comment]
@aaron-collier :speech_balloon: 
> So unless this is configurable, I can really only determine that an update has happened (which may be sufficient), or send along the original SPARQL query... Or do the parsing in the proxy and send along any info we want.

Agreed, these seem like our two best options. As to where we should be parsing the SPARQL queries, I was thinking the ingest service was perhaps more appropriate than the downstream lambda, since services can be more sophisticated than lambdas (ideally), but I can be convinced otherwise!

**Comment by jcoyne** [comment]
@mjgiarlo why would we use a "SPARQL loader component in the RIALTO Combine" if we could use a JSON-LD loader which specifically gives the URIs?  I'm pretty sure that the RIALTO Combine would not be the only consumer. I thought this was in place for Vitro cross functionality.  Is that right? If so can we guarantee that Vitro isn't doing any queries like "Change the name to 'Mike' for the person(s) currently named 'Michael'"

**Comment by mjgiarlo** [comment]
@jcoyne The SPARQL Update loader is in the Combine for community alignment, yeah, in order to support compatibility with VIVO/Vitro 1.x.

I'm not sure I follow your question about guarantees. Why would Vitro be querying itself to (e.g.) change family names across the board? Vitro exposes a SPARQL Update API over HTTP. Clients using that API are free to submit SPARQL Update requests to that endpoint. We are building the Combine, so we have complete control over how it hits the SPARQL Update API.

**Comment by cmh2166** [comment]
so this is a bit of a mess at the moment, and has a lot of misunderstandings of the RIALTO core needs through out. I'll try to work on editing one comment to respond to issues or repeat understandings.

**Comment by cmh2166** [comment]
from @jcoyne :
> @cmh2166 I have some questions about the Lambda architecture. I'm wondering why we don't send the entity directly to the lambda for update. This would avoid an extra query/tranform step for each inserted document.

Because the whole idea is not to hard code the connection between the datastore ingest and the transform code, but instead the transform code to some sort of notification system or cron job. This works around the issue identified in Vitro / VIVO of only one derivative datastore population being supported, and supported via changing code that is core to the canonical datastore.

> I'm also wondering how we know the affected URIs for a SPARQL update? It seems like the proxy would have to parse the SPARQL and figure out if it could resolve which URIs are affected. Is that right?

Yes, this is the messaging need we discussed last week for supporting piece-meal data derivation updates.

> If we're unable to determine affected URIs, do we need a mechanism for drop and rebuild the whole index? If we do that, do we run into availability concerns during the rebuild?

We were holding on to the hope of having a full rebuild option regardless, so yes. But as a cron job type of deal (e.g. run nightly or when explicitly triggered by a RIALTO data admin). The messaging was more for piecemeal updates, which we all agreed would be a really nice feature to add and possibly lessen the rebuild time overall.

**Comment by cmh2166** [comment]
From @mjgiarlo : 

> @cmh2166 It looks great! Here are my questions for the team:
> Why does the SPARQL stack look so different from the JSON one? I wasn't expecting that. I perhaps naïvely assumed the SPARQL proxy would be an endpoint exposed by the Ingest service.

Because when proposed last wednesday morning, it was something to get a handle on the messaging needs, and originally proposed to be Ruby so we could leverage eventually the ruby RDF libraries / gregg kellogg's work, I thought. When I returned to work on Thursday morning, it had become a JSON only REST API using Go and Swagger, due to dev decisions. I don't want to kill this thread because it could be helpful as a feature idea in the future, but it's not helpful any long for what we need for the MVP with messaging work becoming clearer, so the SPARQL Proxy work was separated out.

> I'm curious about the Traject Combine naming (vs. RIALTO Combine which I've seen elsewhere)
> How do folks feel about relabeling the Combine writers as loaders (aligning more closely with ETL terminology)?

This is a request directly from Tom, and what the community is calling this ingest project now. RIALTO ETL == RIALTO Combine (Traject Combine in the diagram is mainly to clarify its using Traject+ work).

> I believe the SPARQL stuff is in progress. @aaron-collier ?
A work-able pass is in the Go Swagger Ingest service codebase, but see comments above on Go Swagger ingest service codebase. Before leaving Weds, @aaron-collier did mention he was picking up breaking this work out into a separate lambda approach.

**Comment by cmh2166** [comment]
from @aaron-collier :  

> - the response I'm getting back from Neptune when doing an insert is:
> 
> 2018/06/27 21:40:36 Response = [
> {
>     "type" : "UpdateEvent",
>     "totalElapsedMillis" : 1,
>     "elapsedMillis" : 0,
>     "connFlush" : 0,
>     "batchResolve" : 0,
>     "whereClause" : 0,
>     "deleteClause" : 0,
>     "insertClause" : 0
> },
> {
>     "type" : "Commit",
>     "totalElapsedMillis" : 14
> }
> 
> So unless this is configurable, I can really only determine that an update has happened (which may be sufficient), or send along the original SPARQL query... Or do the parsing in the proxy and send along any info we want.
> 
> Something to discuss for sure.

We already knew this response quite well, and we already know that it is not configurable. Per our numerous discussions over the last few days, SPARQL query parsing or fall back to a full reindex are the options. I don't see this needing further discussion at this point, but some code and a refinement of our messaging. 

Something also missed by folks: the proposed message in the architecture diagram includes a `body` field where you can dump the whole query as a back up. This was originally added so we could bring the JSON ingest stuff back into alignment and not break the messaging system (since it just adds the whole JSON POST body afaict to the message). That can be a fall back area as well for complex parsing requirements / where it is more than simply an array of subject URIs.

**Comment by peetucket** [comment]
If it simplifies the technical architecture or choices, you can remove full delete as a requirement for the first phase of this RIALTO work.  I am more confident that we will need an update mechanism (for example, a researcher leaves Stanford and we'd like to indicate this as a change to their affiliation status, for example).
