### ISSUE TITLE
Extract SPARQL proxy from rialto-api to lambda

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#128]
Pull the SPARQL proxy code (https://github.com/sul-dlss-labs/rialto-api/blob/master/services/sparql_proxy.go) into a lambda to satisfy https://github.com/sul-dlss/rialto/wiki/RIALTO-Architecture

**Comment by cmh2166** [comment]
Before calling in ops, ensure the steps here (whether through awscli or console, the steps are the same) have been followed to create an executionRole that can create + access ENIs on our rialto-core VPC then link that executionRole to the sparql-loader lambda. 
https://docs.aws.amazon.com/lambda/latest/dg/vpc.html
ENI docs here https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ElasticNetworkInterfaces.html

**Comment by aaron-collier** [comment]
Thanks @cmh2166, reviewing now.

**Comment by aaron-collier** [comment]
Done in https://github.com/sul-dlss-labs/sparql-loader
