### ISSUE TITLE
What sort of interactions are required by the web app?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#129]
This may influence the backing store that we need to use.

Specifically, what kind of interactions can the users have to generate these CSV reports (https://github.com/sul-dlss/rialto/wiki/Web-App-Data-Requirements) and the network diagram and the heatmap?  Can they refine the csv results by searching, filtering and faceting in the web app?  What sorts, filters and facets are needed? Do we want to display the resulting tables on the web or are they download only?

Since "Blacklight" seems to be a hard requirement, what parts of blacklight do we need to have? (e.g. search on field1, field2, facet on field 3).

**Comment by cmh2166** [comment]
See #38 where this was originally meant to be answered.

**Comment by mjgiarlo** [comment]
Since #38 is already closed, I believe we can close this issue now.
