### ISSUE TITLE
Enumerate data source documentation and sample records

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#13]
Citations/publications:
* Web of Science API (XML SOAP, has throttling limitations coincident with production sul-pub)
* SUL-PUB database (combo of direct database access and/or API)

Biographical data:
* CAP Profiles API

SeRA:
* currently not available (example Excel)

**Comment by cmh2166** [comment]
confirm: for this phase of work, we only have 2 sources - WOS API, CAP API. SeRA is marked as next addition as a source once it is available. Everything else is stretch / out of scope for this phase of work (this work cycle). @peetucket confirm?

**Comment by peetucket** [comment]
confirmed -- we still do not have a SeRA API or firm documentation....if/when it comes during the workcycle, we can decide how to incorporate if at all
