### ISSUE TITLE
Document and test Solr setup in AWS

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#130]
What is involved in setting up Solr in AWS? Fall back plan given the answer: Set up Rialto-Dev Solr collection in SUL SolrCloud

**Comment by mjgiarlo** [comment]
@tingulfsen you may also want to ping @cbeer about his experience working on this within the Hydra-in-a-Box project, where at least a couple different deployment strategies were used (ECS, Elastic Beanstalk), in case there are lessons learned that can inform our direction.

**Comment by tingulfsen** [comment]
I briefly spoke with Julian today. He would really prefer that Rialto use the existing (local) SolrCloud that DLSS uses for our current Blacklight/Rails applications, for cost reasons. While it may also seem simpler to just use our own local instance of SolrCloud, we're not going to be able to do that in the near term for the following reasons:

- Our DLSS SolrCloud is protected by firewall rules, which are guaranteed to prevent any code deployed to AWS from connecting. The way around this is to get information on the Stanford-specific subnet/IP addresses that have been set aside for our university in Amazon's cloud. The owner of this information is UIT. This request should go through Julian.
- There is apparently a need for development/infrastructure work on our existing SolrCloud.

Julian said that we won't be able to use our own SolrCloud for Rialto *production or staging purposes* for "several months". He therefore recommended that we go with the simplest possible AWS setup that could possibly work.

**Comment by tingulfsen** [comment]
I'd like to propose that we use a single-EC2-instance Solr setup for Rialto:

- EC2-specific instructions are available at https://lucene.apache.org/solr/guide/7_2/aws-solrcloud-tutorial.html
- I think we can get away with a single node setup as described in the regular Solr setup here: https://lucene.apache.org/solr/guide/7_2/installing-solr.html
- Note that we must set explicitly set the root volume on the EC2 instance to be persisted between reboot/termination events, as explained at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html#Using_RootDeviceStorage

**Comment by tingulfsen** [comment]
See https://github.com/sul-dlss/rialto/wiki/RIALTO-Solr-Setup
