### ISSUE TITLE
Create CSV reports in web-app using fixture data

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#153]
Should have:

1. Basic blacklight search/browse
1. List of visualizations
1. Catalog of reports for download

Blocked by #174

**Comment by mjgiarlo** [comment]
@jcoyne is this closeable now?

**Comment by jcoyne** [comment]
We don't have a catalog of reports listed....so, do we need to add that still?

**Comment by mjgiarlo** [comment]
@jcoyne Yeah, we do. And we have the list o' requested reports here: https://github.com/sul-dlss/rialto/wiki/Web-App-Specs#csv-reports

**Comment by peetucket** [comment]
Will need to be de-composed into separate reports and depends on

**Comment by jcoyne** [comment]
@mjgiarlo I meant to say, we don't have that list available in the webapp.

**Comment by mjgiarlo** [comment]
We're going to load real data and use that to iterate on the CSV reports and visualizations (decided as part of Sprint 13 planning). Closing.
