### ISSUE TITLE
Confirm visualization library to generate  heatmap interaction fits the use case

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#154]
The heatmap should show collaboration countries for all researchers at Stanford.

Using either fixture or hardcoded data, confirm the heatmap visualization library we want to use is visually suitable for the use case it will fulfill.

**Comment by mjgiarlo** [comment]
@jcoyne do you believe the plotly choropleth will work for our purposes based on what we've seen so far? if so, we can close this issue.

**Comment by jcoyne** [comment]
yes.
