### ISSUE TITLE
Review terraform practices and policies with ops - schedule meeting

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#160]
Schedule meeting with ops to discuss:
- [x] Review structure of terraform-aws repository
- [x] Discuss policies related to regions
- [x] Confirm expectations and practices related to our use of terrform (and prs, etc)
- [x] Is `terraform-aws` the best place for project related infrastructure (especially modules) to go? Especially considering that you can reference GitHub modules within your Terraform code (i.e. decoupling).
- [ ] Are any automation tools (i.e. https://www.runatlantis.io/) being investigated/planned?
- [x] Should we consider enabling  state locking e.g. via Terragrunt or a build server like Jenkins or CircleCI?
- [x] Who should/can merge PRs?
- [x] Once PRs have been merged, who should apply changes?
- [x] Within `https://github.com/sul-dlss/terraform-aws/tree/master/organizations/development`, should we consider making project-specific sub-directories?
- [x] What is the current plan for configuring AWS resources? Puppet? Or should we focus on something like Docker?

- Add more as needed -

**Comment by julianmorley** [comment]
I've created a google doc with these questions in and shared it with the Rialto team.

**Comment by aaron-collier** [comment]
Closing per discussion with Jon and doc being completed by Julian and team.
