### ISSUE TITLE
Discuss use case(s) around manual rebuilds of the derivative datastore

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#168]
@jcoyne raised the suggestion of simplifying our implementation of how we trigger rebuilds. He suggested we consider having CloudWatch send the SNS message itself. This raises the question of how we should handle manual rebuilds. @mjgiarlo will chat with @cmh2166 about the use cases around manual rebuilds. Specifically, who will be doing these and via what mechanism? Is triggering via a web UI a requirement?

If we do consider this alternative implementation, the subtasks would include:

- [ ] Change CloudWatch event to send the rebuild SNS message instead of spinning up a lambda to do the same
- [ ] Document how to manually trigger a rebuild using the AWS CLI
- [ ] Delete the rialto-trigger-rebuild lambda
- [ ] Delete the rialto-trigger-rebuild GitHub repo
- [ ] Revise the architecture diagram to reflect these changes

**Comment by cmh2166** [comment]
This should be a whole team thing imo, to set good practices about who changes what in architecture. This ask after doing approach isn't great.

**Comment by mjgiarlo** [comment]
@cmh2166 We haven't done anything yet.

**Comment by cmh2166** [comment]
@mjgiarlo I'm reacting to this, which negates your statement above and reflects a decision, not a discussion:
![Screen Shot 2018-07-17 at 1.54.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58584afbee22740e00479f9d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f46b7191a379f1172f4f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ee5d865097dc56e12f9e9821abc04b3208a1984b2b98a48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ae94b55ad113e65e47e2431.png)

**Comment by mjgiarlo** [comment]
@cmh2166 I can see how you could get that impression from the one-liner above. Sorry for the miscommunication. No decisions were made. @jcoyne suggested an alternative implementation for triggering rebuilds, and I wanted to accurately document 1) what he was proposing, and 2) what would be required to act on it, so that we could discuss use cases around manual triggers and determine if this was a change worth prioritizing.

**Comment by peetucket** [comment]
leave as is
