### ISSUE TITLE
Document data model  for the viz and CSV output

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#174]
Fixture data will likely take the form of DB export format.

See CSV report types here: https://github.com/sul-dlss/rialto/wiki/Web-App-Specs#csv-reports

Blocked by #179

**Comment by mjgiarlo** [comment]
Followed by https://github.com/sul-dlss-labs/rialto-webapp/issues/18

**Comment by mjgiarlo** [comment]
Have initial data model documented: https://github.com/sul-dlss-labs/rialto-webapp/wiki/RIALTO-Derivative-Database-Data-Model Will improve iteratively as needed. Closing.
