### ISSUE TITLE
Select webapp data stores required for phase 1

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#18]
- how do we get data from the RIALTO datastore to our visualization or other webapp code?
- is solr a good fit for this?
- what data shape is required for JS framework?
- do we need any other information for the data to be useful to the JS framework?
- what performance (or infrastructure) do we need to support realtime viz?

blocked by #25

**Comment by cmh2166** [comment]
needs to be enumerated / decided before we can add these derivative data functions to the canonical data store (i.e. Vitro0

**Comment by mjgiarlo** [comment]
1. Solr
2. RDS

Closing.
