### ISSUE TITLE
Apply naming/structure best practices to AWS dev environment

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#191]
Per our conversation with AWS liaisons this morning:

- [ ] Break up rialto-core SG into multiple SGs and apply those SGs (do not open up ports unnecessarily)
- [ ] Name everything (and name everything more descriptively, ideally specifying env, service, port, etc.)
- [ ] Assign tags where appropriate
- [ ] Clean up VPCs (and SGs)
- [ ] Decide if we need public and private subnets (if yes, create NAT/gateway to make connections between them)

**Comment by aaron-collier** [comment]
1. is covered by #194.
2. & 3. are covered by Terraform implementation
4. & 5. are covered by ops practices of VPC and subnet ids.
#208 added to clean up dev in us-east-1
