### ISSUE TITLE
Set up DNS for the webapp to get a persistent URL

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#192]
Every time we deploy a new version of a ECS task the public IP is going to change. So we probably need a load balancer and attach a stable IP to that load balancer and then associate a DNS with that IP

See
https://forums.aws.amazon.com/thread.jspa?threadID=270599
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted.html (Search for "Application load balancing")

**Comment by aaron-collier** [comment]
As part of the ECS deployment in terraform, the dev name of rialto.dev.sul.stanford.edu has been registered.
