### ISSUE TITLE
Break up / define execution roles

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#195]

**Comment by tingulfsen** [comment]
https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/rialto-sparql-loader-development?tab=graph

contains the error message "The API with ID g6x94d9jg0 does not include a resource with path /* having an integration arn:aws:lambda:us-west-2:418214828013:function:rialto-sparql-loader-development on the ANY method." which means that we have to fix the execution role.

**Comment by aaron-collier** [comment]
Fixed here: https://github.com/sul-dlss/terraform-aws/blob/rialto-dev/modules/local/aws/lambda/permission/main.tf#L12
