### ISSUE TITLE
Use terraform to deploy to AWS dev environment

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#199]
Includes:

- [x] Deploy Solr via ECS (using an ALB so it has a static IP) instead of EC2
- [x] Set up ALB for ECS-based web application
- [ ] ...

@tingulfsen and @aaron-collier to unpack :point_up: further after this afternoon's meeting with @jonrober

**Comment by mjgiarlo** [comment]
I believe we have this understanding now, per #202.

**Comment by mjgiarlo** [comment]
Here's my conundrum: the webapp specifies the Solr URL as an env variable. Once we put Solr behind ECS, its IP address will change over time. I attempted to create an ALB for an ECS-based Solr instance, but the `rialto-core` VPC is only in one availability zone (`us-east-1a`) and ALBs *require* at least two subnets which *must* be in different availability zones. Mentioned on Slack a minute ago, and @aaron-collier suggested a meeting with @jonrober about this.
