### ISSUE TITLE
API or data mechanism between the RIALTO datastore and the UI

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#20]
This is separate from the need for a data connection between the RIALTO datastore and realtime viz (see #18).

How does data get served from RIALTO datastore (see #16) and the webpages / search and discovery / etc.

**Comment by jgreben** [comment]
Perhaps some of the code here is worth looking at (if only just to say why we wouldn't want to do it this way): https://github.com/sul-dlss-labs/sparql_to_sw_solr

**Comment by cmh2166** [comment]
closed in favor of #38
