### ISSUE TITLE
Identify changes made in dev for SOLR to Webapp

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#202]
@mjgiarlo changes...

**Comment by mjgiarlo** [comment]
After pairing on this with @jcoyne today, we concluded that the relevant changes here are about VPCs---not about ECS task roles---specifically which SGs are used (and which inbound rules they specify) and which subnets are used.

**Comment by mjgiarlo** [comment]
@cmh2166 :point_up:

**Comment by cmh2166** [comment]
looks good to me - anything else you wanted me to add?

**Comment by mjgiarlo** [comment]
@cmh2166 Nope! Didn't want to close this if you were inclined to look at it further yet. Will close. Thanks for taking a gander.
