### ISSUE TITLE
Document AWS & Terraform practices

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#209]
We have agreed to document our current practices and policies covering AWS/Terraform in Consul:

https://consul.stanford.edu/pages/viewpage.action?title=Terraform+and+AWS&spaceKey=dlssdevops

In addition, we would like to add READMEs to the various Terraform modules, as well as variable `description` tags.

**Comment by tingulfsen** [comment]
To avoid different work cycles stepping on each other, we would like to propose that:

- Each team uses their own `-dev` branch (e.g. `rialto-dev`) within the terraform-aws repository AND
- Each team uses their own state file (with a unique name)

**Comment by tingulfsen** [comment]
Further documentation requests from team members:

- [ ] Overview of the DLSS repos involved
- [ ]  A note about folder scope
- [ ]  Terraform command primer (which are the most useful, what they do (in brief), and any gotchas)
- [ ]  How to test changes that I make (to discover errors as early as I can)

**Comment by mjgiarlo** [comment]
@tingulfsen I made some basic changes to https://consul.stanford.edu/display/dlssdevops/Terraform+and+AWS for some of the bullets above. It would be good for someone with more experience to take on the remaining ones (I'm not :100: clear on which repos are legacy vs. which are current.)

**Comment by tingulfsen** [comment]
Closed via https://github.com/sul-dlss/rialto/wiki/Terraform-and-RIALTO and https://consul.stanford.edu/display/dlssdevops/Terraform+and+AWS
