### ISSUE TITLE
Investigate potential visualization libraries and their data requirements

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#21]
Explore usage possibly of:

- D3.js
- C3.js
- other visualization libraries we could use in the UI

blocked by #25 blocked by #38

**Comment by jgreben** [comment]
http://js.cytoscape.org

**Comment by mjgiarlo** [comment]
Document the visualizations as required by the RIALTO user stories, including what the entities are, what the "joins" are, and what fields might be required (or useful) to display. The purpose of this work is to begin defining what shape data in the viz data store needs to take (and, e.g., what fields need indexing and how).

**Comment by mjgiarlo** [comment]
Are you inclined to take a look at this one, @jgreben?

**Comment by jgreben** [comment]
[WIP] see https://docs.google.com/spreadsheets/d/1qMFY8Z-ndYSynMFZ-6lIMGhfhy79Hkr2WaerulXwJUA/edit#gid=0

**Comment by mjgiarlo** [comment]
Awesome, @jgreben!

**Comment by jcoyne** [comment]
Shouldn't we have a UX designer look at what visualizations we need to build before we select a tech solution?

**Comment by mjgiarlo** [comment]
@peetucket :point_up: :question:

**Comment by peetucket** [comment]
We had limited access to a UX designer (late last year it was Jennifer) and we can request for more time as we get closer to the design/development of the front end, though I suspect our use of that designer would be more optimized if we went into the conversation with some possible frameworks.  There is likely to be some negotiation between the designer, the dev team and the product owner about the relative merits/costs of various solutions.  Particularly in the first phase, we'll likely want to keep the design costs low (and trade of usability and/or visual design as a result).

**Comment by jcoyne** [comment]
@peetucket designing the user experience should be the most important thing.  Our technology choice depends on what we want to achieve and not the other way round.  If we can't find a solution to what is in the designs, then we can have a conversations about adjusting designs to meet technical considerations.

**Comment by jcoyne** [comment]
It seems like we need to look at a solution for heatmaps and network diagrams.

**Comment by peetucket** [comment]
sounds right

**Comment by mjgiarlo** [comment]
It seems we're going to go with Plotly for now and will re-assess if that doesn't fit our needs. Closing.
