### ISSUE TITLE
Make organization transformer conform to current RIALTO data model

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#212]

**Comment by jcoyne** [comment]
Possibly drop `dbo:alias` from https://github.com/sul-dlss-labs/rialto-etl/blob/master/mapping.md#for-organizations

**Comment by jcoyne** [comment]
I'm not sure what we need to do on this ticket.  For the most part the organization transformer already conforms with the RIALTO data model with the exception of `dbo:alias` as stated above.
