### ISSUE TITLE
Confirm full team has access to Stanford Profiles API and grant access to those who don't have it

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#214]
Tick off your name when you can confirm you have access to this resource: https://cap.stanford.edu/cap-api/console

- [x] @mjgiarlo
- [ ] @jcoyne 
- [ ] @aaron-collier 
- [x] @tingulfsen 
- [x] @peetucket
- [ ] justin l

If you do *not* have access, drop a comment here asking @peetucket to request access on your behalf.

**Comment by mjgiarlo** [comment]
@peetucket :point_up: 

Related: do we all have access to this potentially useful resource? https://cap.stanford.edu/cap-api/console

**Comment by jcoyne** [comment]
@mjgiarlo I was unable to connect to that potentially useful resource. I got an "Unauthorized"
 message.

**Comment by mjgiarlo** [comment]
Aha. @peetucket can you help with that?

**Comment by aaron-collier** [comment]
@peetucket I also get the unauthorized message.

**Comment by peetucket** [comment]
Will request access once Justin L starts and has a sunet

**Comment by aaron-collier** [comment]
He may/should have one already as I recall it being a requirement something like a week or so a head of my start for orientation.
