### ISSUE TITLE
Restrict access to web-app (all environments) via shibboleth to specific workgroup

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#219]
The web-app should not be available to everyone on campus (so restricted to Stanford VPN is still too permissive).  We need to restrict access to specific users, and the best scenario is behind a shibboleth auth challenge to a defined workgroup (which would need to be created and seeded to include us and our stakeholders).

- [ ] add shib component to terraform
- [x] @peetucket to create new workgroup and dlss-developers to this workgroup ... workgroup is  `sul:rialto`
- [ ] add new workgroup name to auth compontent
- [ ] implement for all environments
- [ ] remove VPN only access for web app

**Comment by mjgiarlo** [comment]
@peetucket Can we break this up into short-term and longer-term components? Thinking the network-level security restrictions can be handled during this sprint, and we can deal with the Shib requirement when we know more about it. How's that sound?

**Comment by peetucket** [comment]
That sounds totally reasonable.  Do we need a new ticket for short-term lock down via VPN or does #194  cover it?

**Comment by mjgiarlo** [comment]
@peetucket I suspect #194 does already cover it. 

@aaron-collier @tingulfsen Confirm/deny?
