### ISSUE TITLE
VPC cleanup

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#223]
We should use a single VPC for everything - check this using the AWS Console. If required, fix up the Terraform code.

**Comment by tingulfsen** [comment]
Note that there are currently 3 VPCs in the Oregon region:

- <unnamed>
- development
- development-other

We should keep only the one named development and delete the other two.

**Comment by aaron-collier** [comment]
@tingulfsen it looks like the RDS instance is getting into the unnamed VPC. Once we clean that up I think it can be removed.

**Comment by aaron-collier** [comment]
I was able to remove the `unnamed` VPC once we moved RDS out of it. the `development-other` does not look like something related to any rialto work and I will open a separate ops ticket on it.
