### ISSUE TITLE
Terraform: Create S3 bucket for lambda uploads - document process for how they are created

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#224]
Our current bucket was manually created. Let's make sure the creation of the bucket is automated. Note that this ticket does NOT require anything other than creating the S3 bucket itself.

**Comment by aaron-collier** [comment]
The production bucket was already created, but the staging bucket was removed. Will be added in this PR: https://github.com/sul-dlss/terraform-aws/pull/142
