### ISSUE TITLE
Profile/benchmark RIALTO Core from SPARQL Proxy API to a Derivative Datastore (Solr or other)

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#230]
- where are sys usage blockers?
- are there optimizations we can make in re-index triggers?
- are messages or jobs being dropped from SNS topic if Neptune overused?

**Comment by aaron-collier** [comment]
I believe we've captured this in the wiki and follow up issues/PRs, if not we can reopen clarify.
