### ISSUE TITLE
Refactor terraform-aws development directory to use a project-specific subdirectory

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#233]
We're currently developing our main Terraform code within https://github.com/sul-dlss/terraform-aws/tree/rialto-dev/

For the development organization (https://github.com/sul-dlss/terraform-aws/tree/rialto-dev/organizations/development), we should add a project-specific directory called `rialto` instead of just putting all the code in organizations/development/.

- [X] Import State
- [x] Import Resources

**Comment by aaron-collier** [comment]
This has been completed and deployed with @jonrober
