### ISSUE TITLE
Finalize Solr and database Terraform setup to ensure persistence of data

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#234]
Our AWS Solr service is defined using an EC2 image. This is problematic for security reasons. We need to figure out how we might keep Solr up to date:

- Use ECS instead?
- Create new AMI images when needed?
- etc.

**Comment by aaron-collier** [comment]
Blocked by #278

**Comment by mjgiarlo** [comment]
Looks like the blocking issue was closed a few weeks ago. Is this still blocked or should we move to Ready? @aaron-collier

**Comment by aaron-collier** [comment]
Closing as data persistence is in place, will add a few documentation tasks.
