### ISSUE TITLE
Terraform: Use variables instead of hard-coded values for container definitions

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#236]
Some of the RIALTO-specific Docker containers currently use hard-coded values where we would like to use variable names. We should implement variables as shown here:

https://github.com/sul-dlss/terraform-aws/blob/master/modules/local/shibboleth/main.tf#L5-L16

**Comment by aaron-collier** [comment]
https://github.com/sul-dlss/terraform-aws/pull/136
