### ISSUE TITLE
Pass error codes from Neptune to clients of proxy API

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#241]
When the gateway sees the `BadRequest` prefix it should return a 400 status code.  All other responses should remain as 200.  See https://github.com/sul-dlss-labs/sparql-loader/pull/14

**Comment by aaron-collier** [comment]
PR here: https://github.com/sul-dlss/terraform-aws/pull/141

**Comment by aaron-collier** [comment]
Closed via https://github.com/sul-dlss/terraform-aws/commit/202e4f4f3d1f6b66a859a838babb18cca9a77db6 and https://github.com/sul-dlss-labs/sparql-loader/pull/28
