### ISSUE TITLE
Terraform: Increase lambda timeout to 5 minutes?

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/rialto#242]
We should consider increasing the timeout for the SPARQL Loader lambda to more than the current 90 seconds. Today some of our test requests ran for over 2 minutes.

**Note:** I manually set the limit to 5 minutes today (i.e. in the AWS Console, not within Terraform).

**Comment by aaron-collier** [comment]
Added in this PR: https://github.com/sul-dlss/terraform-aws/pull/141
