### ISSUE TITLE
How to handle Neptune timeouts

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#246]
Note: Just capturing notes here for discussion.

- After deleting all records, I saw the CPU on neptune spike
- While CPU was high, got timeouts
- Was able to run single, on-off queries using the sparql proxy
- Running a data load seems to be the source of spiking the CPU (Anywhere from 80% - 99%)
- Neptune does an automated restart

Odd error in the Events:
```
Error restarting database: Communications link failure The last packet successfully received from the server was 10,566 milliseconds ago. The last packet sent successfully to the server was 10,570 milliseconds ago..Unable to: SELECT count(*) from mysql.plugin WHERE name = ?
```

**Comment by aaron-collier** [comment]
I'm also walking through the S3 bulk load example and get the following error output:

```
curl -X POST  -H 'Content-Type: application/json'  http://rialto-dev.clqwjadk8neo.us-west-2.neptune.amazonaws.com:8182/loader -d '
 {
   "source" : "s3://rialto-data-load/mapped_entities.nt",
   "format" : "ntriples",
   "iamRoleArn" : "arn:aws:iam::418214828013:role/NeptuneS3Load",
   "region" : "us-west-2",
   "failOnError" : "FALSE"
}'
{"requestId":"86b2b263-9c54-9010-e043-67fc83de8e4e","code":"InvalidParameterException","detailedMessage":"Failed to start new load from the source s3://rialto-data-load/mapped_entities.nt. Couldn't find the aws credential for iam_role_arn: arn:aws:iam::418214828013:role/NeptuneS3Load"}
```
Note, that this is also the case when I use the DeveloperRole ARN

**Comment by jcoyne** [comment]
when we send a properly escaped request, this is no longer occurring.

**Comment by rashmipriya** [comment]
Can you please share the request @jcoyne ? I am getting the same error and I am not able to resolve the same.

**Comment by jcoyne** [comment]
@rashmipriya sorry, this was a long while ago and I forgot.
