### ISSUE TITLE
Investigate why Terraform doesn't create Lambda triggers and have it done automatically if possible

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#247]
We would expect this to do it, but it doesn't seem to.
https://github.com/sul-dlss/terraform-aws/blob/37e38a08585bd797629c501829aad2640717768b/organizations/development/rialto.tf#L604-L614

**Comment by jonrober** [comment]
Not sure, is this relevant?  https://github.com/terraform-providers/terraform-provider-aws/pull/5024

**Comment by aaron-collier** [comment]
I think we need to add a permission like we do for api gateway: https://github.com/sul-dlss/terraform-module-aws-lambda/blob/master/permission/main.tf... According to: https://github.com/hashicorp/terraform/issues/10748

**Comment by aaron-collier** [comment]
Fixed.
