### ISSUE TITLE
Version lambdas for releases

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#248]
https://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html

This should help us identify exactly which version/branch of a lambda is running

**Comment by aaron-collier** [comment]
This is blocked pending ops questions:

- [ ] When we deploy LAMBDAs to production, has any consideration been put into how we should handle versioning? It does not appear that terraform can actually create a version, only aliases against existing versions. 
- [ ] Who/How do we update lambda versions through CLI or Console? OpsRequests?
- [ ] What about CI/CD? In dev, we've been able to use the role in circleci to update the lambda on a merge to master. It seems like we are going to need to define something of a manual workflow for production vs. something automated... Any thoughts/ideas here are more than welcome, just trying to capture for docs/code.

**Comment by mjgiarlo** [comment]
Tagging @jonrober here to make sure he's aware of the above.

**Comment by jonrober** [comment]
Aaron and I've discussed a bit already and basically need to sit down and walk through it more directly since I'm not experienced with lambdas.

**Comment by mjgiarlo** [comment]
@aaron-collier @jonrober What's the status of this issue? Still blocked?

**Comment by aaron-collier** [comment]
@mjgiarlo yes, this is still blocked. I don't think the current assumptions of production AWS will allow this versioning, so @jonrober, @tingulfsen and I probably need to walk through what this workflow should look like so we can inform production rules and roles.

**Comment by aaron-collier** [comment]
Closing this as we are not using this approach in production. It will possibly come back up, but now is not a concern.
