### ISSUE TITLE
Need palettes, fonts, final designs for web app

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#250]

**Comment by astridu** [comment]
Hello, you can find the 3 images on the home page (the faded photo behind the icons) here: https://drive.google.com/open?id=12eYvku0lgJuG4oWkPSCZrxzbDvHWXXmx

Everything else is a font or html. I invited Peter to the Invision file. You can click on the Inspect button </> at the bottom of the page, and it will give you the code for all the styles. LMK if you have any trouble with the invitation. It sometimes goes to spam.

Thanks!
Astrid

**Comment by astridu** [comment]
I think someone on your team has worked with fontawesome, but here's some info just in case you need it. https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
