### ISSUE TITLE
Add rialto-entity-resolver to terraform build

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto#255]
Add the rialto-entity-resolver container to terraform and include in next deploy.

**Comment by aaron-collier** [comment]
Currently blocked by:

```
* aws_acm_certificate.cert: Error requesting certificate: LimitExceededException: Error: you have reached your limit of 20 certificates in the last year.
	status code: 400, request id: 0a276260-b839-11e8-945c-5da0588c85ae
```

**Comment by mjgiarlo** [comment]
@jonrober When you can confirm this has been done, can you drop a comment on this issue? Thanks!

**Comment by jonrober** [comment]
The certificate increase went through.  The push is on Aaron's end in terraform code he was writing.

**Comment by mjgiarlo** [comment]
Thanks, @jonrober. This is no longer blocked. Moving back to In Progress. FYI, @aaron-collier

**Comment by aaron-collier** [comment]
Unblocked and done.
