### ISSUE TITLE
WOS transform should create sponsors if they don't already exist

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#259]
Supersedes #26 

Use the entity resolver service to determine if sponsors already exist as agents in RIALTO Core.

- [ ] Create a URI immediately in a named graph associated with WoS
- [ ] Associate them to the publication with a `vivo:informationResourceSupportedBy` entity

**Comment by justinlittman** [comment]
@mjgiarlo @jcoyne Do you have any examples of a publication with sponsors?

**Comment by mjgiarlo** [comment]
@justinlittman I'll check and reply here soon.

**Comment by mjgiarlo** [comment]
@justinlittman There are a bunch in the `rialto-sample-data` repository in the `raw/pubs/` directory. Look at the files matching `WOS:{ID}.json` in particular.

Also, I just updated the mapping with the following based on what I'm seeing in these records:

> Send grant ID strings from `$.static_data.fullrecord_metadata.fund_ack.grant.grant_ids.grant_id` to the RIALTO entity resolver. **Note** that the `.grant` node may be either an object or an array, and the `.grant_id` node may be either a string or an array. (There are four different possibilities that your JSON Path will need to accommodate.) Use the returned URIs, or create new ones.
