### ISSUE TITLE
create WOS to RIALTO MAP mapping

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#26]

**Comment by mjgiarlo** [comment]
Using one or more sample WoS records and the [MAP for RIALTO publications](https://github.com/sul-dlss/rialto/wiki/RIALTO-Data-Models-&-Profiles#publications-aka-documents-or-citations), document the mapping here: https://github.com/sul-dlss-labs/rialto-etl/wiki

**Comment by mjgiarlo** [comment]
First pass of this is now done: https://github.com/sul-dlss-labs/rialto-etl/wiki#publications-wosweb-of-science-mapping

**Comment by mjgiarlo** [comment]
Closing this issue now that follow-up issues have been created.
