### ISSUE TITLE
Share Terraform demo

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#267]
Now that @aaron-collier has shared the shiny new [Terraform demo video](https://youtu.be/tk9vsPpdcw0) (per #253) with the team, we ought to share it out. 

- [ ] @peetucket to share w/ dlss-all-staff, VIVO #rialto channel, and stanfordlibs #sprint-demos channel
- [x] @mjgiarlo to share on Twitter

**Comment by mjgiarlo** [comment]
My part is done: https://twitter.com/mjgiarlo/status/1042150906576297984

**Comment by peetucket** [comment]
Shared with VIVO Tech Google Group, DLSS-ALL, rialto-announce and VIVO slack channel.
