### ISSUE TITLE
Build facet by three different organization units in website and see people linked to those organizational units

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#270]
The designs (https://projects.invisionapp.com/d/main#/console/15093987/313922044/preview) include facets for "Department", "Institution" and "School", but the data for these call come from the Profiles API and are part of the same hierarchy. Faceting by each of these various levels of academic unit should limit by the people in those units.

blocked by #269
blocked by #268
blocked by #sul-dlss-labs/rialto-etl#139

**Comment by jcoyne** [comment]
Currently we have a "Department" facet which links to people.  Department is one kind of organization.  Do we need others?

**Comment by peetucket** [comment]
The designs include facets for "Department" and "Institution" and "School", but the data for these call come from the Profiles API and are part of the same hierarchy.  While this gives us a nice user experience, if we aren't indexing the data in a way that allows us to separate those levels of the hierarchy into facets, we could combine in a big list for this workcycle (with a term like "Academic Unit").

**Comment by jcoyne** [comment]
@peetucket I don't have a preference for what we take on here, but this ticket as written is too ambiguous.  Can we write something more specific?
