### ISSUE TITLE
Run ETL for publication data into RIALTO Core (Dev) from WoS API to view publication data in website from server

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#271]
blocked by sul-dlss-labs/rialto-etl#100
blocked by sul-dlss-labs/rialto-etl#110
blocked by #272
blocked by sul-dlss-labs/rialto-etl#192

- [x] wipe all Neptune data
- [x] wipe and manually rebuild derivative stores
- [x] [run full ETL](https://github.com/sul-dlss-labs/rialto-etl/wiki/RIALTO-Combine-Load-Procedure) up to, but **not** including, the WoS/pubs step
- [x] extract pubs data from WoS API
- [x] transform pubs to SPARQL
- [x] commit to `rialto-sample-data` repo
- [x] ~~load pubs in Neptune~~ [run full ETL](https://github.com/sul-dlss-labs/rialto-etl/wiki/RIALTO-Combine-Load-Procedure) from the WoS/pubs step
- [x] document any steps that aren't well documented
- [x] view website
  - [x] ensure pubs, orgs, grants, researchers all present (and appropriately linked together)
  - [x] ensure position URIs are not malformed
  - [x] ensure WoS authors have `prefLabel`s
  - [x] ensure name variants for researchers work

**Comment by mjgiarlo** [comment]
All entity types have run through ETL and we will handle future bugs as new issues. We will now handle ETL runs using a schedule, to better mimic how this will be dealt with in production. Closing.
