### ISSUE TITLE
Iterate over all people with sunetIDs and pull grants from SeRA API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#273]

**Comment by mjgiarlo** [comment]
@peetucket I assume we meant grants rather than publications here, but do we mean "all authors" or "all people with SUNet IDs ?"

**Comment by peetucket** [comment]
thanks, correct on both counts, updated the title

**Comment by mjgiarlo** [comment]
Here's what I did:

1. `exe/extract call StanfordResearchers > researchers.json`
2. `jq --raw-output '.uid // empty' researchers.json | sort > sunetids.txt`
3. `for id in $(cat sunetids.txt); do echo $id; exe/extract call Sera -s $id > ../rialto-sample-data/raw/grants/grouped_by_sunetid/$id.json; done`

And now... :watch: ...

**Comment by justinlittman** [comment]
Don't forget that there is `exe/transform call StanfordPeopleList`.

**Comment by mjgiarlo** [comment]
Re-assigning this to @tingulfsen who has picked up this work.

**Comment by mjgiarlo** [comment]
This is done. All grants have been pulled and committed to the sample-data repo. Closing.
