### ISSUE TITLE
Evaluate opportunities to parallelize SeRA ingest for performance improvements

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#283]

**Comment by peetucket** [comment]
also, can we eliminate certain classes of sunet from polling (e.g. students?)

**Comment by mjgiarlo** [comment]
FWIW, here's how the research data breaks down by affiliation:

```shell
jq '. as $record | .affiliations | keys[] | select($record.affiliations[.] == true)' researchers.json | sort | uniq -c | sort -nr
  38279 "capStaff"
  21170 "capRegistry"
   7003 "capFaculty"
   5380 "capPhdStudent"
   5082 "capMsStudent"
   2488 "capPostdoc"
   2374 "physician"
   1002 "capResident"
    547 "capFellow"
    510 "capMdStudent"
```

**Comment by peetucket** [comment]
I would guess that we could skip the pulling of grants for `capPhdStudent`, `capMsStudent` and `capMdStudent` -- that's 11k right there.

Is there a 1:1 relationship between affiliation and person?  or do we really have >70k people ?

**Comment by peetucket** [comment]
ok, didn't realize there were that many people, but I double checked and that is roughly the same size of "active" users in sul_pub (actually we have more, not sure why though)

**Comment by mjgiarlo** [comment]
@peetucket alas...

```
   1423 "capFaculty"
    427 "physician"
     84 "capStaff"
     57 "capRegistry"
     26 "capPostdoc"
      5 "capMsStudent"
      4 "capFellow"
      2 "capResident"
      1 "capPhdStudent"
      1 "capMdStudent"
```

Every affiliation except `capOther` (so far) has grants.

**Comment by peetucket** [comment]
Huh, interesting.  Those 5 MS Students with grants are going places
