### ISSUE TITLE
Person profile question

### ISSUE THREAD

**Issue by vivnwong** [sul-dlss/rialto#289]
Determine whether we want to list everyone within the department, or only list people with certain profiles. For example, within Profiles.stanford.edu, the School of Medicine only list profiles with Faculty, Research and Teaching Staff, Staff, Postdocs, Graduate Students (9332 matches). RIALTO lists 11477 entries, and the extra names include administrative staff, temp, non-exempt etc.

**Comment by jcoyne** [comment]
Should we add a facet with subtype of person? @peetucket @astridu

**Comment by peetucket** [comment]
yes
