### ISSUE TITLE
Create a new alarm for scaling down

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#290]
Currently the scaling down is using the same CloudWatch alarm as the scale up.  I’m pretty sure we need a different alarm for scaling down.  See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch_alarm_autoscaling.html
> (Optional) You can also create another alarm that triggers when the memory reservation is below 25%, which you can use to remove a container instance from your Auto Scaling group.

**Comment by aaron-collier** [comment]
Closing this in favor of a ticket in the module: https://github.com/sul-dlss/terraform-module-aws-ecs/issues/13
