### ISSUE TITLE
Create Docker-based dev environment

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/rialto#291]
Create and document a docker-based development environment.

**Comment by justinlittman** [comment]
Depends on:
* https://github.com/sul-dlss-labs/rialto-etl/issues/187
* https://github.com/sul-dlss-labs/rialto-webapp/issues/89
* https://github.com/sul-dlss-labs/rialto-derivatives/issues/102
and:
* https://github.com/sul-dlss-labs/rialto-dev/pull/1

**Comment by justinlittman** [comment]
No longer depends on https://github.com/sul-dlss-labs/rialto-webapp/issues/89 but depends on https://github.com/sul-dlss-labs/sparql-loader/pull/51

**Comment by peetucket** [comment]
Confirm that another developer can get local dev environment setup and complete documentation as needed

**Comment by peetucket** [comment]
Add a wiki page to the rialto wiki that describes what a new developer has to do to get started (could just point to the correct README)

**Comment by mjgiarlo** [comment]
@peetucket @justinlittman I have now gotten `rialto-dev` up and running. The README has been updated in a few places, and it's now linked to our project wiki. Per above, I am closing this issue.
