### ISSUE TITLE
Physicians may have Faculty and NonAcademic

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto#293]
See these affiliations: https://gist.github.com/jcoyne/9c2689b51f772b61d348eaf93fcd4fc7#file-profile-json-L456

It seems as though we are applying this rule correctly:
![2018-10-16_1123](https://user-images.githubusercontent.com/92044/47028361-e249fa80-d12e-11e8-868e-26167c080792.png)

However it seems incorrect for this person to be both Faculty and NonAcademic as those are disjoint concepts. Should we apply all matching rules, or only the first matching rule from that set?

**Comment by jcoyne** [comment]
Either choice is fine with Christina, decision deferred to @peetucket. 

* Use Stanford specific types rather than VIVO types
* Apply all sub-types that apply.  We will be okay with the edge cases such as the one presented having Faculty and NonAcademic.

Regardless of the choice made, ensure our code can handle a person with multiple specific types.

**Comment by peetucket** [comment]
* Use Stanford types
* Make available in browse
