### ISSUE TITLE
Web App Usability Issues

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#306]
This is a placeholder issue to take note of usability issues in the website.  These may be broken into individual tickets later (please remove or link from the list if this happens).  Actual bugs (existing features that are obviously broken instead of just non-optimal or missing) should get their own issues right away.

- [x] Reduce font size on home page icons so they fit better

Items with issues already:
- "Start over" button for the browse section (i.e. clear all fitlers) -- sul-dlss/rialto-webapp#77
- Radio button or redesign to allow for "all stanford", "school" or "department" filters on collaboration reports -- sul-dlss/rialto-webapp#169
- Formatting of text in facets in browse is a challenge, we need to play with fonts, alignment, text truncation or some combination of all to distinguish facet values from facet counts from "X" de-selector -- sul-dlss/rialto-webapp#170
- Paging and searching in the browse is just slow enough that users may not think anything is happening after clicking a pagination link...I don't think the current method of display "searching..." is enough to get their attention, explore some alternate ways of making it clear something is happening -- sul-dlss/rialto-webapp#171
- Pagination link improvements -- sul-dlss/rialto-webapp#172
- Navigational improvements/breadcrumbs in browse   -- sul-dlss/rialto-webapp#173
- Active Search term/facet indicators -- sul-dlss/rialto-webapp#175
- Truncate or remove publication abstract from search results (some are just too long for a search results page, and they are visible on the publication entity detail page anyway)  -- sul-dlss/rialto-webapp#176
- Paginate collaboration co-author report -- sul-dlss/rialto-webapp#177
- Terminology/label updates  -- sul-dlss/rialto-webapp#178

**Comment by jcoyne** [comment]
Can we close this since we have tickets for all the items?

**Comment by peetucket** [comment]
yes, will do
