### ISSUE TITLE
Request a virtual machine for vitro

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#31]
"beefy"

**Comment by mjgiarlo** [comment]
Follow this documentation: https://consul.stanford.edu/display/dlssdevops/How+to+spec+a+new+server

**Comment by mjgiarlo** [comment]
Information we need to specify to [request a VM](https://consul.stanford.edu/display/dlssdevops/How+to+spec+a+new+server):

* name of machine
  * `rialto-vitro-dev`?
* # of CPUs
* Amount of RAM
* Amount of storage needed by Vitro instance?
* Amount of storage needed for Vitro logs?
* Preferred username for application to run under?
  * `vitro`?
* List of SUNet IDs with access to the host

**Comment by kamchan** [comment]
With the 500GB storage requirement, it would be good to have the rialto app in its home dir on a dedicated /opt/app/rialto partition (local disk) while the application data itself (bulk of its storage) live on an nfs mount (ie /rialto)?

**Comment by mjgiarlo** [comment]
@kamchan I'm not sure where Vitro stores its data or how much control we have other that. Would it be possible to begin by allotting a single smaller partition (say 50GB), and then reconfiguring the host later when we know more? (Maybe @cmh2166 knows better, so I'm tagging her in here.)

**Comment by kamchan** [comment]
sure, we can initially allocate 50G for the app.

**Comment by cmh2166** [comment]
@tommyi reviewed + approved specs for today (per standup)

**Comment by mjgiarlo** [comment]
SAR ticket: https://jirasul.stanford.edu/jira/browse/SAR-3519

Leaving this issue open until the host is created and I can connect to it.

**Comment by mjgiarlo** [comment]
I can now connect to the host. Thanks, @kamchan!
