### ISSUE TITLE
Provision new server for running production etl jobs

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#310]

**Comment by aaron-collier** [comment]
https://jirasul.stanford.edu/jira/browse/SAR-3550

https://github.com/sul-dlss/operations-tasks/issues/1793

@mjgiarlo this came up during standup, so I took the liberty of reviewing the original rialto-vitro requests and opening the -prod request.

**Comment by aaron-collier** [comment]
Done.
