### ISSUE TITLE
Figure out how many publications have concepts/topics

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#315]

**Comment by peetucket** [comment]
Compare raw data against derivative data to be sure the data is being indexed correctly

**Comment by justinlittman** [comment]
The answer appears to be that they all do based on:
```
cat wos-*.ndj | jq '[.static_data.fullrecord_metadata.category_info.subjects.subject[] | select(.ascatype == "extended")] | length != 0' | grep 'false'
```

**Comment by peetucket** [comment]
ok, well that's good, but then i would expect those reports that rely on topics to have much bigger aggregated numbers
