### ISSUE TITLE
Enumerate ingest options for vitro

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#33]
Investigate and enumerate the options for ingesting data into vitro

- [X] Answer this question: can we access Jena directly?
- [x] Consult Jim Blake
- [x] Consult the VIVO community via Slack

**Comment by peetucket** [comment]
For each option identify, run a smoke test and collect metrics of sample large data set

#35 has the first option, create additional tickets for the other options

**Comment by cmh2166** [comment]
@tingulfsen looking at connecting directly through the java endpoints to the appropriate triplestore. Very similar to how Cornell Weill approaches connecting through Jena via Java. Troll through codebases here: https://github.com/wcmc-its

**Comment by cmh2166** [comment]
Also, request to try reloading some data through SPARQL over HTTP VIVO ingest endpoint with the inferencing turned off

**Comment by jgreben** [comment]
Some of the relevant code is in: `Vitro/api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/api/SparqlUpdateApiController.java`

**Comment by jgreben** [comment]
The Vitro java code ^^ is accessible via a tomcat servlet that takes a request with an `update` param. The request string is literally the `update=INSERT DATA {}` wrapper syntax for the inserted triples. The SparqlUpdateApiController.java class takes the value of `update` as a string and sends that to a Jena library class to perform the update.

Basically I think that hacking the java code to load data will only buy us the avoidance of passing a potentially large string over http to the tomcat servlet and it's associated class. The largeness of the string is not really a major issue because tomcat can be configured to handle large post requests with the `maxPostSize` connector attribute and additional tomcat tuning.

Otherwise, we could probably write a java wrapper class to call the SparqlUpdateApiController with the same update string as an argument, but I'm not so sure that seeking to avoiding the servlet layer will give us much of a serious performance boost. It would probably be better to just tune tomcat to be performant in case we run into issues.

**Comment by jgreben** [comment]
This may contain some ideas about running the war file classes outside of tomcat:

https://stackoverflow.com/questions/1842972/how-do-i-run-a-class-in-a-war-from-the-command-line

**Comment by tingulfsen** [comment]
Consider asking the VIVO community/Slack for listing ingest options, then creating new tickets for actually doing the ingest. Document options in the sul-dlss/rialto Wiki.

**Comment by jgreben** [comment]
Please take a look at https://github.com/sul-dlss/rialto/wiki/Vitro-Data-Ingest-Options

The Vitro code sample links were provided in consultation with Huda Kahn at Cornell. The samples are not necessarily from or in the release version that we are using. Still to do is to ask Jim Blake and/or the community via Slack.

**Comment by cmh2166** [comment]
This looks great to me and exactly what we needed.

**Comment by mjgiarlo** [comment]
@jgreben :clap:

**Comment by jgreben** [comment]
More from convos w/ Huda:  We should also keep in mind that at Cornell, when they do an update they do have to stop things for some hours, and there's also search index rebuilding time to take into account.

**Comment by mjgiarlo** [comment]
@jgreben I tweaked the description above to include the subtasks you mentioned earlier this week. Did I get those right?

**Comment by jgreben** [comment]
@mjgiarlo Yes. Jim Blake replied that he was swamped and would get back to me soon. Once I hear from him whether we are on the right track, I will send out a message on slack to wrap it up.

**Comment by cmh2166** [comment]
is there just a way to infer from the existing dataIngest channel + docs (for point 3)? If so, I'm happy to take this on this weekend if it isn't done today.

**Comment by jgreben** [comment]
Thoughts and reactions from Jim Blake:
```
Jena TDB
Configuring Vitro to use Jena TDB is easy (applicationSetup.n3)
There are good reasons to use Jena TDB instead of Jena SDB. TDB might well be the best choice. Don’t know.
For standard VIVO installation, Jena SDB is still the default.
I don’t know of anyone who is using Vitro or VIVO in production with a large triple-store based on Jena TDB – the community will not be able to provide input with regard to performance or reliability.
Going “behind Vitro’s back”
If you use methods 1., 2., or 5., you are working with Vitro. This means that your changes will be noted by listeners that do (a) simple inferencing, and (b) search index update.
If you use methods 3., 4., 6., or 7., you are working around Vitro. This means that you must insure correct inferencing and index updating on your own. Some VIVO sites operate this way. Most do not.
Swapping data stores
For high availability, one can imagine building an updated triple-store and an updated search index, and then swapping them into a live Vitro instance. This is easy to do with the search index, since every query is a stateless HTTP connection. For Jena TDB, you would need to add code that would close all open connections, flushing the memory buffers, and then open new connections. Vitro currently has no such code.
Pausing the indexer
This should not be a problem. There are internal API calls that wil pause and unpause the indexer.
Is the same true for the reasoner? (inferencing)
 
1. Load data using the SparqlUpdate API
2. Load data using Vitro data loading abstractions (TDB Java API).
3. Jena SPARQL Update API (ARQ: direct loading via SPARQL not http)
4. Jena SDB (JDBC) Connection.
5. Load data as a filegraph
6. Use Jena Tdbloader
7. Fuseki
```

**Comment by peetucket** [comment]
From https://jena.apache.org/documentation/sdb/ 

``` Use of SDB for new applications is not recommended. This component is "maintenance only". TDB is faster, more scalable and better supported than SDB. ```

**Comment by cmh2166** [comment]
Being cleaned up here: https://github.com/sul-dlss/rialto/wiki/Vitro-Data-Ingest-Options
