### ISSUE TITLE
Enumerate options for the middle layer of how the web application gets data from the canonical datastore

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#38]
- solr
- postgres
- ~data distribution API~

**Comment by cmh2166** [comment]
Perhaps some of the code here is worth looking at (if only just to say why we wouldn't want to do it this way): https://github.com/sul-dlss-labs/sparql_to_sw_solr

**Comment by tingulfsen** [comment]
Enumerate and document how data can be pulled out of our VIVO/Vitro instance.

**Comment by jcoyne** [comment]
@cmh2166 didn't we discuss yesterday how this was blocked until we selected a datastore. Have we done so?

**Comment by cmh2166** [comment]
@jcoyne because you guys have still not confirmed what is on the webapp side.

**Comment by cmh2166** [comment]
question here has now become: what do we need for the simple RIALTO Web app, which is mostly likely Blacklight / rails. Exploration currently: Elasticsearch (1 or multiple indices?) in Blacklight.

**Comment by peetucket** [comment]
Faceting or searching within fields is not needed to fulfill the top use case reviewed and approved by OIA (https://jirasul.stanford.edu/jira/browse/RIALTO-8).  The data that is used to produce the heat map visualization can be restricted down with filters:

1. Date filter - to restrict the publications used to those published within that date
2. Organizational unit filter (department, school, etc.) - to restrict authors returned to those that belong to that organizational unit

The resulting publications from these filters are then used to determine the co-authorish lists (which include the co-author institutions).  These are used to make the heatmap.

This same data that results after these two filters are selected can be exported as a CSV, but doesn't have to be further searched or filtered.

**Comment by peetucket** [comment]
And as I look through the several use cases below this one, the trend is similar - a top level filter to reduce the scope of the data being used to generate the CSV or the visualization, but no explicit need to facet or search on the reduced data set once produced (or even to search to reduce the scope in the beginning).

The next question is, assuming the ability to couple filtering with search is added in a future phase (or require faceting after the visualization is produced), how, if at all, does this affect the choices that are made now.   Perhaps not at all, and that complexity is punted for when/if the project has a second phase of development.  But I think its at least worth considering even if not in the initial stated requirements.

**Comment by cmh2166** [comment]
This is going to be messaging system that performs sparql queries, maps to a document, and writes to solr.
