### ISSUE TITLE
Add rialto-vitro-dev's Shib ID to RIALTO workgroup & confirm working

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#40]
- [ ] Add rialto-vitro-dev's Shib ID to the sul:rialto workgroup (requested by @kamchan on May 10th) and repuppetize rialto-vitro-dev
   - [ ] Confirm Vitro is still accessible by sul:rialto users via Shib (@mjgiarlo)

(Follow-on ticket to #32.)

**Comment by kamchan** [comment]
UIT came back with the shib workgroup changes.  After testing out the workgroup changes in apache on rialto-vitro-dev, it looks like UIT has some missing attributes that still needs to be added.  I've sent them an email with those details.  We'll see what they say.

**Comment by mjgiarlo** [comment]
Thanks for following up, @kamchan

**Comment by kamchan** [comment]
UIT got the right attributes set so we are now workgroup shib protected.  We can close this if no other comments.

**Comment by mjgiarlo** [comment]
Thank you, @kamchan! Closing.
