### ISSUE TITLE
Document methods for continuous delivery (for our Vitro customizations)

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#42]
In particular we're looking to do the following:

* Continue using GitHub to manage source control
* Use one or more branches to trigger delivery
* Integrate with maven on `rialto-vitro-dev`

Note that third-party services like GitHub and TravisCI do not have access to `rialto-vitro-dev` which is behind a Stanford firewall, so a mechanism that relies on a push from one of these services won't work for us.

**Comment by mjgiarlo** [comment]
I believe @jgreben was interested in this issue. (I'm not going to assign it, though, since I know he's on other work.)

**Comment by jgreben** [comment]
@mjgiarlo what do you  think about using capistrano to deploy code to the server, without using TravisCI? I've had success doing this with the Symphony registry-harvester.

**Comment by mjgiarlo** [comment]
@jgreben Fully automated would be lovely, but semi-automated with some documented, easy steps will definitely be an improvement over the fully manual state we're in now. I'm totally open to that.

**Comment by jgreben** [comment]
We got this set up with travisCI on a -dev box: https://travis-ci.org/sul-dlss-labs/ld4p-marc21-to-xml. If the firewall situation is the same maybe we can see if it's possible to do this. I think the details are in the secure api_key.

```
deploy:
  provider: releases
  api_key:
    secure: 'xyz123pqr456'
```

**Comment by jgreben** [comment]
Completed by #4 and #36 which sets up deployment and deploy tasks using the standard DLSS Capistrano deploy methodology.
