### ISSUE TITLE
Reach out to Ops wrt Performance Metrics

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#48]
What performance metrics can Ops grab (or they would want us to grab) as part of https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

**Comment by mjgiarlo** [comment]
@jgreben That's awesome. I'm looking at the stats during @tingulfsen's import run last night:

https://sulstats.stanford.edu/dashboard/db/servers?from=1526619600000&to=1526655600000&var-department=dlss&var-project=rialto&var-server=rialto-vitro-dev&theme=light

Interesting stuff there. Looks like RAM maxes out a bunch of times and needs to use swap briefly around 3am. CPU, I/O, and load look solid throughout.

**Comment by cmh2166** [comment]
if it answers all the provided questions in https://github.com/sul-dlss/rialto/wiki/Performance-Assessment#metrics-gathered-for-each-case then we can close this ticket i think.

**Comment by jgreben** [comment]
Submitted https://github.com/sul-dlss/operations-tasks/issues/1633

**Comment by mjgiarlo** [comment]
@kamchan estimates this may be done by the end of the week.

**Comment by mjgiarlo** [comment]
This is now done.
