### ISSUE TITLE
Performance Assess: SPARQL API (Vitro) no Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#50]
1 SPARQL API (Vitro) full sample data load without inferencing & with indexing.

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

**Comment by jgreben** [comment]
`/opt/app/vitro/data/rialto-sample-data/vivo/load.log`

**Comment by mjgiarlo** [comment]
https://sulstats.stanford.edu/dashboard/db/servers?from=1526619600000&to=1526655600000&var-department=dlss&var-project=rialto&var-server=rialto-vitro-dev&theme=light

**Comment by mjgiarlo** [comment]
Above is the system metrics during the time this load was running (10pm last night until 8am this morning, roughly).

**Comment by jgreben** [comment]
•	Sample Data Load Times
	◦	Total time to load all sample data -> 03:53 to 09:15 [5:20 min]
	◦	Time per RDF record / file -> 0.25 seconds
	◦	Time per request (if multiple requests, i.e., HTTP) -> 0.25 seconds
	◦	Scaling graph based on the above -> see below

**Comment by jgreben** [comment]
<img width="640" alt="screen shot 2018-05-24 at 1 30 49 pm" src="https://user-images.githubusercontent.com/3093850/40512163-c230a770-5f56-11e8-9ffe-fb2a52e6030d.png">

<img width="627" alt="screen shot 2018-05-24 at 1 30 21 pm" src="https://user-images.githubusercontent.com/3093850/40512168-c66265a4-5f56-11e8-87e6-6aeefb3948a0.png">

<img width="625" alt="screen shot 2018-05-24 at 1 30 40 pm" src="https://user-images.githubusercontent.com/3093850/40512173-cb448c1e-5f56-11e8-9d92-e359868a620a.png">

**Comment by jgreben** [comment]
Sheet with sample data points: https://drive.google.com/open?id=1UipIX0zsQnwcBTsCKb6dg1F5OsGkLGSJ

**Comment by jgreben** [comment]
Dashboard: https://sulstats.stanford.edu/dashboard/db/servers?from=1527133800000&to=1527153600000&var-department=dlss&var-project=rialto&var-server=rialto-vitro-dev
