### ISSUE TITLE
Performance Assess: SPARQL API (Vitro) with Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#51]
1. SPARQL API (Vitro) full load w/ inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

Blocked by #74

**Comment by tingulfsen** [comment]
This task ran in 5h 22m on our server, using one request per file.

<img width="1634" alt="screen shot 2018-05-22 at 18 39 33" src="https://user-images.githubusercontent.com/3740294/40402450-9e091140-5e00-11e8-81be-9e78c6d19777.png">

**Comment by cmh2166** [comment]
leave to EOD monday or whenever we need this server.

**Comment by mjgiarlo** [comment]
This is now complete.
