### ISSUE TITLE
Performance Assess: JENA TDBLoader with Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#56]
2 Jena TDBLoader (cmd line) full load w/inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

blocked by #44 (confirm indexing trigger works even when loading into TBD directly / not via Vitro code)

**Comment by mjgiarlo** [comment]
The team has dismissed tdbloader as a loading option per our [findings](https://github.com/sul-dlss/rialto/wiki/Loading-data-into-Vitro:-Jena-tdbloader#findings). Closing this issue.
