### ISSUE TITLE
Performance Assess: Jena SPARQL Update (ARQ) no Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#59]
3 Jena SPARQL Update (ARQ) full load w/o inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

**Comment by cmh2166** [comment]
Question from @jcoyne : for Jena with TDB, does this just leverage the same APIs that tdbloader does. If that is true here, then does this ingest option get knocked out? cc: @mjgiarlo @jgreben

**Comment by jcoyne** [comment]
Almost that.  It's calling the TDB api (not tdbloader, which is something different).

**Comment by cmh2166** [comment]
Okay, your questions remains, yes?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgreben** [comment]
The tdbloader command-line utility ultimately uses this: https://github.com/apache/jena/blob/master/jena-tdb/src/main/java/org/apache/jena/tdb/TDBLoader.java, so yeah, it's essentially the same thing from a performance standpoint. The main difference is the potential to develop hooks into the listeners, solr, etc., if feasible.

**Comment by tingulfsen** [comment]
We ran this on the server in a total time of 68 seconds, per the Unix `time` command. The logging output is attached below: 

[59_log.txt](https://github.com/sul-dlss/rialto/files/2086372/59_log.txt)

**Comment by tingulfsen** [comment]
Note that upon attempting to issue a SPARQL query from the Vitro UI immediately afterwards, we got the usual `BlockAccessBase: Bounds exception: /opt/app/vitro/home/tdbContentModels/node2id.idn: (1031,1)` 500 error.
