### ISSUE TITLE
Performance Assess: Jena SPARQL Update (ARQ) with Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#60]
3 Jena SPARQL Update (ARQ) full load w/inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

Blocked by #72 Blocked by #74

**Comment by tingulfsen** [comment]
We ran this in 69s. See the log below.

Note that upon attempting to issue a SPARQL query from the Vitro UI immediately afterwards, we got the usual BlockAccessBase: Bounds exception: /opt/app/vitro/home/tdbContentModels/node2id.idn: (1031,1) 500 error. This requires a Tomcat restart.

[60_log.txt](https://github.com/sul-dlss/rialto/files/2086485/60_log.txt)
