### ISSUE TITLE
Performance Assess: Jena SPARQL Update (ARQ) no Inferencing, no Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#61]
3 Jena SPARQL Update (ARQ) full load w/o inferencing & w/o indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

blocked by #44 blocked by #45

**Comment by jcoyne** [comment]
Ran:
```
 time java -cp "lib/*:." RialtoArq ~/home/tdbContentModels ~/data/rialto-sample-data/vivo/agents
```

on rialto-vitro-dev after clearing out the data directory. Tomcat was running as we did the import.

```
real	1m10.532s
user	1m20.425s
sys	0m6.359s
```

When I attempted to run this sparql select query:
```
SELECT ?s ?p ?o
WHERE
{
  GRAPH <http://vitro.mannlib.cornell.edu/default/vitro-kb-2> { ?s ?p ?o }
}
LIMIT 1000
```

 in order to verify the import Vitro gave this error:

```
HTTP Status 500 - BlockAccessBase: Bounds exception: /opt/app/vitro/home/tdbContentModels/node2id.idn: (1031,1)
```

After restarting Tomcat, then the query ran with the expected results.

**Comment by jcoyne** [comment]
It's our hypothesis that this `BlockAccessBase: Bounds exception` is how TDB is manifesting it's restriction that it can only be used by one JVM at a time. This restriction makes this approach untenable.
