### ISSUE TITLE
Performance Assess: TDB Java API (Vitro) with Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#62]
4 TDB Java API (Vitro) full load w/ inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

**Comment by tingulfsen** [comment]
We ran this in 63s. See the log below.

Note that upon attempting to issue a SPARQL query from the Vitro UI immediately afterwards, we got the usual BlockAccessBase: Bounds exception: /opt/app/vitro/home/tdbContentModels/node2id.idn: (1031,1) 500 error. This requires a Tomcat restart.

[62_log.txt](https://github.com/sul-dlss/rialto/files/2086479/62_log.txt)
