### ISSUE TITLE
Performance Assess: TDB Java API (Vitro) no Inferencing, with Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#63]
4 TDB Java API (Vitro) full load w/o inferencing & w/indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

**Comment by tingulfsen** [comment]
We ran this scenario on the server using our own RialtoLoad Java class. It ran in 64s, see the log output below:

[73_inferencing_off.log](https://github.com/sul-dlss/rialto/files/2086376/73_inferencing_off.log)

**Comment by tingulfsen** [comment]
Note that upon attempting to issue a SPARQL query from the Vitro UI immediately afterwards, we got the usual `BlockAccessBase: Bounds exception: /opt/app/vitro/home/tdbContentModels/node2id.idn: (1031,1)` 500 error.
