### ISSUE TITLE
Verify Capistrano deploy and remove old source directory

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/rialto#64]
Did all the code with the recent codebase changes deploy and install correctly? Does anything else need to change before removing the old source directory under `/opt/app/vitro/src/`?

**Comment by jgreben** [comment]
Moved `src/` to 'src_old/', restarted tomcat, visited https://rialto-vitro-dev.stanford.edu/vitro/startupStatus and everything looks normal. All of the smoke tests and setup steps pass.

**Comment by mjgiarlo** [comment]
@jgreben Excellent! Thank you!
