### ISSUE TITLE
Performance Assess: JENA TDBLoader with Inferencing, no Indexing

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#67]
2 Jena TDBLoader (cmd line) full load with inferencing & w/o indexing

see https://github.com/sul-dlss/rialto/wiki/Performance-Assessment

blocked by #45 blocked by #44 need to confirm indexing + inferencing within Vitro is not triggered or can be turned on or off when loaded directly into TDB

**Comment by mjgiarlo** [comment]
The team has dismissed tdbloader as a loading option per our [findings](https://github.com/sul-dlss/rialto/wiki/Loading-data-into-Vitro:-Jena-tdbloader#findings). Closing this issue.
