### ISSUE TITLE
Document how to load data into Vitro: Jena SPARQL Update

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#72]
Do that here: https://github.com/sul-dlss/rialto/wiki/Loading-data-into-Vitro:-Jena-SPARQL-Update-(ARQ)

Blocks #59
Blocks #60
Blocks #61
Blocks #62

**Comment by jcoyne** [comment]
See https://wiki.duraspace.org/display/VIVODOC110x/SPARQL+Update+API#SPARQLUpdateAPI-Insertexample for the upstream docs.

**Comment by tingulfsen** [comment]
ARQ docs are here: https://jena.apache.org/documentation/query/

**Comment by tingulfsen** [comment]
The documentation is now up, so I am closing this ticket.
