### ISSUE TITLE
Document how to load data into Vitro: TDB Java API

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#73]
Do that here: https://github.com/sul-dlss/rialto/wiki/Loading-data-into-Vitro:-TDB-Java-API

Blocks #62 Blocks #63

**Comment by jgreben** [comment]
Started a pass at it here: https://github.com/sul-dlss/rialto/wiki/%5BWIP%5DLoading-data-into-Vitro:-TDB-Java-API

**Comment by jgreben** [comment]
I think this is documented as much as it needs to be at this point.
