### ISSUE TITLE
Document how to tell that inferencing is enabled and functioning in Vitro

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#74]
The imports for #50 and #51 took roughly the same amount of time, which the team found surprising; our expectation was that #51 would take longer because inferencing was enabled. That raises a question: how can we tell that inferencing is indeed enabled and working? This issue is to document how to confirm inferencing is turned on and working in Vitro.

Blocks #67, #62, #60, #56, #51

**Comment by jgreben** [comment]
This is useful:
https://wiki.duraspace.org/display/VIVODOC19x/Graph+Reference

**Comment by jgreben** [comment]
Documented at https://github.com/sul-dlss/rialto/wiki/Inferencing:-how-to-tell-it-is-enabled-and-functioning-in-Vitro

**Comment by mjgiarlo** [comment]
Excellent. Thanks, @jgreben. Closing.
