### ISSUE TITLE
Load sample data into BlazeGraph using SPARQL update endpoint

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#78]

**Comment by tingulfsen** [comment]
We loaded our sample data set into BlazeGraph in 2 ways:

- One file at a time, using curl: `curl -X POST http://localhost:8080/blazegraph/namespace/rialto-test-1/sparql --data-urlencode 'update=LOAD <file:///opt/app/vitro/data/rialto-sample-data/vivo/agents/zz572.nt>' -H 'Accept:application/rdf+xml'` (full script in `/opt/app/vitro/blazegraph/bload.sh` on `rialto-vitro-test`). This load took 17m 30s.
- As one huge file, also using curl: `curl -X POST http://localhost:8080/blazegraph/namespace/rialto-test-2/sparql --data-urlencode "update=LOAD <file:///tmp/everything.nt>"`. This load took 23s (plus xxx to generate the single large file from all the smaller ones in the test set).

**Comment by tingulfsen** [comment]
For more information, see https://wiki.blazegraph.com/wiki/index.php/REST_API
