### ISSUE TITLE
Document TDB vs BlazeGraph for datastore

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#80]
We are looking at BlazeGraph in particular because it is connected to Neptune, so we need to describe why/how this is an alternative to TDB

**Comment by jcoyne** [comment]
Explain why TDB is troublesome and why Blazegraph is a preferred option.

**Comment by tingulfsen** [comment]
- Blazegraph comes with an extensive REST API. With TDB you have to implement Fuseki separately.
- Blazegraph lets you do full text search using SPARQL with Solr as a back end, while TDB provides the same functionality but using Lucene or Elasticsearch.

**Comment by jcoyne** [comment]
https://github.com/sul-dlss/rialto/wiki/Comparing-triple-stores

**Comment by cmh2166** [comment]
fantastic, thank you @jcoyne
