### ISSUE TITLE
Discussion with Ops about possibilities of using AWS for RIALTO

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#81]

**Comment by jcoyne** [comment]
On 2018-06-11 4:02 PM Julian said on slack:
> Not in production yet.
>
> Folks can experiment on laptops, or running docker engine on VMs, but for production loads we'd need to do some additional work.

**Comment by cmh2166** [comment]
awaiting key(s) from Ops. promised by 11 am today.

**Comment by cmh2166** [comment]
closed in favor of #86
