### ISSUE TITLE
specify (later in dev, build) AWS infra needed for RIALTO Core

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#88]
i.e. security group, vpc, neptune cluster, parameter groups, ec2 / ecs cluster, sns topic, lambda, + presumed policies between all these

(Was blocked by #86)

related to #136

**Comment by mjgiarlo** [comment]
Do this here (unless there is sensitive information): https://github.com/sul-dlss/rialto/wiki/AWS-Build-Specification

**Comment by mjgiarlo** [comment]
First draft done. Closing.
