### ISSUE TITLE
SNS (or other) to lambda to web app derivative datastores dev setup

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#91]
- run locally / deploy locally with localstack
- where does the lambda + other code live for version control + collab (i.e. 1 lambda per... gist? repo?)
- spit ball process for getting the lambda code as zip file to terraform build space (may be some sort of codebase build step)
- select lambda language (options include python, node, java, go, ?)

**Comment by mjgiarlo** [comment]
The team selected Go as the Lambda language.

**Comment by jcoyne** [comment]
Localstack go support was added very recently in: https://github.com/localstack/localstack/pull/617 So we'll need to use localstack 0.8.7

**Comment by jcoyne** [comment]
As far as I can tell SQS is not a supported event source for Lambda: https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html  Can we use SNS?

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> Localstack go support was added very recently in: localstack/localstack#617 So we'll need to use localstack >= 0.8.6

Heads-up, @tingulfsen @aaron-collier @jgreben

**Comment by mjgiarlo** [comment]
Discussed during storytime today and decided to keep this open until work is deployed.
