### ISSUE TITLE
Write or select RIALTO Core derivative datastore population method

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#92]
Derivative datastore needs currently:
- triplestore (via SPARQL query) to Solr (or Elasticsearch) docs
- triplestore (via SPARQL query) to JSON for Postgres
- ... ? 

Related to #38

What library (or libraries) is needed for lambdas to perform these transforms, and how are mapping specs passed to them?

**Comment by jcoyne** [comment]
In progress in https://github.com/sul-dlss-labs/rialto-api and https://github.com/sul-dlss/rialto/pull/103
