### ISSUE TITLE
devs need to find VIVO community engagement points

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#97]
apps + tools calls? develop slack channel?

- [x] Join vivo-tech list (see below)
  - [x] @mjgiarlo
  - [x] @jcoyne 
  - [x] @aaron-collier 
  - [x] @tingulfsen 
- [x] Get Apps and Tools IG calls on calendar
  - [x] @mjgiarlo
  - [x] @jcoyne 
  - [x] @aaron-collier 
  - [x] @tingulfsen 
- [x] Join VIVO Slack workspace (`#develop` channel)
  - [x] @mjgiarlo
  - [x] @jcoyne 
  - [x] @aaron-collier 
  - [x] @tingulfsen

**Comment by mjgiarlo** [comment]
Join VIVO Slack via http://bit.ly/vivo-slack

**Comment by mjgiarlo** [comment]
Instructions for joining vivo-tech list: https://wiki.duraspace.org/display/VIVO/Email+Lists

**Comment by aaron-collier** [comment]
All have checked the above, so closing.
