### ISSUE TITLE
Install localstack

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/rialto#99]
- [x] @jcoyne 
- [x] @mjgiarlo
- [x] @aaron-collier 
- [x] @jgreben 
- [x] @tingulfsen

**Comment by mjgiarlo** [comment]
Each dev on the RIALTO team should install localstack for easier dev/testing of AWS infrastructure. Start here: https://github.com/localstack/localstack

**Comment by mjgiarlo** [comment]
See also: https://github.com/sul-dlss-labs/taco/blob/master/docs/localstack.md

**Comment by cmh2166** [comment]
this should be done by everyone?

**Comment by mjgiarlo** [comment]
@tingulfsen Have you installed localstack yet? If so, can you tick your box above and close this issue?

**Comment by mjgiarlo** [comment]
@tingulfsen Nevermind. I believe I found in our standup notes that you *have* already done this work, so I am closing the issue.
